
const projects = [
  // Major Projects
  {
    id: 1,
    title: 'Face Recognition System',
    description: 'A Face Recognition System identifies or verifies individuals by analyzing facial features using computer vision and machine learning algorithms.',
    type: 'major',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRljSQjAiqdJaKADxUVHIvI23rzMp-uFacU7g&s',
   demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/Face_Recognition_System-',
    link: 'https://face-recognition-system-pied.vercel.app/',
  },
  {
    id: 2,
    title: 'RKSD College website',
    description: 'RKSD College website, developed by me, offers seamless navigation, student resources, academic updates, and a modern responsive design interface.',
    type: 'major',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1SUtI0BaKx9OmZtF-lJXB3JhZhZyEwexO8Q&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/RKSD-COLLEGE',
    link: 'https://rksdpharma.vercel.app/',
  },

  // Mid Projects
  {
    id: 4,
    title: 'Study IQ UPSC learning website',
    description: 'Study IQ UPSC learning website, basically developed by me, offers essential resources and tools for UPSC preparation.',
    type: 'mid',
    image: 'https://yt3.googleusercontent.com/0buocGKxLKmCMxIO1CjKO1E91bC-thosw5xUkm32x8trmv5IJBq5o2S8Q7rsb6QaUUGwuOFN=s900-c-k-c0x00ffffff-no-rj',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/UPSC_Web_page',
    link: 'https://683a8814bc5b926034b1d6f3--bucolic-kashata-ec6f2a.netlify.app/',
  },
  {
    id: 8,
    title: 'Flipkart Clone ',
    description: 'Flipkart Clone developed by me with core features, responsive design, product listings,',
    type: 'mid',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYDAg3jyR7dcEpkacgR2cEbdu_Z6VEN0TmsQ&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/Flipkart',
    link: 'https://683a8a6df028c826c7bf137b--funny-kleicha-d3a3ca.netlify.app/',
  },
  {
    id: 9,
    title: 'Amazon clone ',
    description: 'Amazon Clone developed by me, replicating core design, layout, and basic functionality for learning and practice purposes.',
    type: 'mid',
    image: 'https://sangvish.com/wp-content/uploads/2021/10/Buy2Market-amazon-clone-script.png',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/Amazon_Clone',
    link: 'https://683a8af3652ef60d2d940f1e--ornate-cascaron-1ccf88.netlify.app/',
  },
  {
    id: 10,
    title: 'HRS Website',
    description: 'HRS Website developed by me with responsive design, showcasing services, team details, and contact information efficiently.',
    type: 'mid',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnGEtETABTG0_6vKFBiMtnH7QvAocv-qIFg&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/HRS_Web',
    link: 'https://683a8716bc5b925efbb1d696--magenta-manatee-b99fa4.netlify.app/',
  },
  {
    id: 11,
    title: 'My Portfolio',
    description: 'A personal portfolio showcasing my skills, projects, experience, and achievements, designed to highlight my professional and creative capabilities.',
    type: 'mid',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThQqhl_05O70oWJ5dJO783-l3sy5vgUVNUYQ&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/My-Portfolio/tree/main/bhushan',
    link: 'https://face-recognition-system-z1rg.vercel.app/',
  },

  // Minor Projects
  {
    id: 7,
    title: 'Tip Calculator',
    description: 'Tip Calculator developed by me to quickly calculate tip amounts and total bills with a simple user interface.',
    type: 'minor',
    image: 'https://cdn.hashnode.com/res/hashnode/image/upload/v1673498174615/a9ff29fc-a3b2-400e-b159-8f1200085c44.jpeg',
    demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://react-js-javascript-9hua.vercel.app/',
  },
  {
    id: 12,
    title: 'Age Counter',
    description: 'Age Counter developed by me to calculate exact age from date of birth using a simple, interactive interface.',
    type: 'minor',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_u4yLGdy-KSdDHF2RrC99uiAYQB-p-zOD5Q&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://age-counter-two.vercel.app/',
  },
  {
    id: 13,
    title: 'Number Counter',
    description: 'A number counter is a tool or program that increments or decrements numerical values, often used for tracking or animations.',
    type: 'minor',
    image: 'https://play-lh.googleusercontent.com/xoNQT2OJoDOtB-uBmzlya5z83A6dpS5eGS4AAOH48BBOP2aROaouKOB-eeVoh-xv8K4',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://react-js-javascript-rqby.vercel.app/',
  },
  {
    id: 14,
    title: 'ADD. sub. IN. DE.',
    description: 'ADD increases value by 1, SUB decreases by 1, IN increments stored variable, DE decrements it; used in counters/forms.',
    type: 'minor',
    image: '/images/addin.png',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://cbroy62.github.io/AddToCard/',
  },
  {
    id: 15,
    title: 'Calculator.',
    description: 'A simple, developer-built calculator for basic arithmetic operations like add, subtract, multiply, and divide using clean, responsive UI.',
    type: 'minor',
    image: 'https://lh3.googleusercontent.com/AL_WQZ1aze_yZin9FN4t624Qsl9n2CqRGGXogYdu6LnI2aASShx_ifvI3ees2W6TBXJ1MquMMqmG6RDMrEjnQR5Bsg=s1280-w1280-h800',
    demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://683bd370f84796e51eb4c327--flourishing-muffin-272995.netlify.app/',
  },
  {
    id: 16,
    title: 'Tic Tac Toe Game.',
    description: 'A simple, classic Tic Tac Toe game developed by me with smooth gameplay, clean UI, and two-player support on one device.',
    type: 'minor',
    image: '/images/tic_toc.png',
    demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'h',
    link: 'https://to-do-list-jade-beta.vercel.app/',
  },
  {
    id: 17,
    title: 'Student Marks Calculator Web App.',
    description: 'A simple web app developed independently to calculate total marks, percentage, and division from five subjects: Hindi, English, Maths, Physics, and Chemistry. Clean UI with instant results.',
    type: 'minor',
    image: 'https://i.ytimg.com/vi/YGDDoad8s9g/sddefault.jpg',
    demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/JavaScript-100-Problem/tree/main/MarksCalculator',
    link: 'https://superlative-tapioca-8c8d16.netlify.app/',
  },
  {
    id: 18,
    title: 'Radius Value Calculator',
    description: 'A self-developed tool to calculate the radius value from user input. Simple interface with input field and instant calculation, ideal for basic geometry-related learning or practice.',
    type: 'minor',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSCEx62LzIJK5GbhE4dONvCy5S_yyh7u2_HA&s',
     demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/JavaScript-100-Problem/tree/main/Radious',
    link: 'https://roaring-mochi-942840.netlify.app/',
  },
  {
    id: 19,
    title: 'Contact Management App (CRUD)',
    description: 'A simple contact management application allowing users to add, edit, save, and delete contact entries with name, email, and phone details using an intuitive interface.',
    type: 'minor',
    image: 'https://www.sourcecodester.com/sites/default/files/images/nurhodelta_17/crud_ss_0.png',
    demoCodeLabel:'Sourse Code',
    buttonLabel: 'Live Demo',
    demoCodeLink: 'https://github.com/CBROY62/JavaScript-100-Problem/tree/main/CURD_Operation',
    link: 'https://heroic-cupcake-bd0fb0.netlify.app/',
  },
   {
    id: 20,
    title: 'Contact(CRUD)',
    description: 'A simple contact management application allowing users to add, edit, save, and delete contact entries with name, email, and phone details using an intuitive interface.',
    type: 'minor',
    image: 'https://www.sourcecodester.com/sites/default/files/images/nurhodelta_17/angular_crud_uirouter.png',
    buttonLabel: 'Live Demo',
    link: 'https://inspiring-twilight-ed1390.netlify.app/',
    demoCodeLabel:'Sourse Code',
    demoCodeLink: 'https://github.com/CBROY62/JavaScript-100-Problem/tree/main/Click_Created_componets',
  },
];

export default projects;
